# config.yaml
dataset:
  name: "Reside_OTS"
  root: "./datasets/RESIDE-OTS" # options: /RTTS/RTTS
  hazy_path: "hazy-part2"
  clear_path: "clear"
  img_size: 256
  return_bboxes: False
  subset: 500 # Max 500 images. Set to False if you want to use full dataset

training:
  device: "cuda"
  batch_size: 2
  lr: 0.0001
  weight_decay: 0.0
  epochs: 20
  num_workers: 0

model:
  name: "LCAnet" # options: AODnet, LCAnet
  save_path: "./runs"
